### ISSUE TITLE
Failure to setup Local-Osu-Server

### ISSUE THREAD

**Issue by BoxDevelopment** [coverosu/local-osu-server#35]
I attempted to follow the instruction in which i was met with errors
i fixed majority of the errors but still fail to be able to allow the web dashboard to launch osu

**Comment by jeevanjohnson** [comment]
From my understanding, you are trying to run LOSv3, LOSv3 in this project specifically isn't going to be maintained and v1 is the most stable version for this project. I need to create a "how to" guide on setting up cloudflare or mitmproxy so it is runnable without my domain because currently I don't have one open. If you are running into problems regarding v1, I can do my best to help, but any other version besides v3 on the organization I won't be able to.

**Comment by BoxDevelopment** [comment]
thats all understandable. could you drop a quick explanation on how to make my own domain to use for the LOSv1. I have a domain just theres none thats working for LOSv1

**Comment by jeevanjohnson** [comment]
I'm about to post on the discord a little tutorial :)
