### ISSUE TITLE
Is this against the terms of osu!?

### ISSUE THREAD

**Issue by SrIzan10** [coverosu/local-osu-server#7]
Hey! I don't want to get my account banned for this experiment, so I have a question: Is this safe? Will I get banned?

BTW: What API key do I need? osu!api v1 or v2?

Thanks!

**Comment by coverosu** [comment]
100% safe and you won't get banned! Been on it forever now and can guarantee you'll be fine :D

For the `main` branch (the working one) you'll need the api v1 key which can be a little tricky to get a first, but is retrievable.
For the `master` branch (devs only) you'll need osu!api v2 api data in order to get that booted up

Hope that answers your questions c:

**Comment by SrIzan10** [comment]
Hey! I still have questions. It asks me for an osu! account or something. I'm skeptical of putting my account credentials on it.When getting the v1 api key it says that is the equivalent to giving your password.

And, why does it need an osu! folder?

**Comment by coverosu** [comment]
It uses your credentials to have the ability to use bancho's (the main server's) direct so that direct on the local server is exactly like bancho's, you can always leave it blank if you don't wanna have direct/feel unsafe just know direct won't work then, but I can assure you you'll be fine!

Since the way I have redirection setup I can't handle score submission properly, so as an alternative I use your osu! replay folder to check for changes and use that as score submission another reason why I use it because from there I can check for osu!trainer maps and handle those accordingly.

**Comment by SrIzan10** [comment]
ty for responding to my concerns!
